### ISSUE TITLE
Passing additional options to input.select

### ISSUE THREAD

**Issue by iainwallacebms** [posit-dev/py-shiny#704] opened 2023-08-24 19:40 UTC
Hi,

Is it possible to pass additional options to input.select? The use case is to allow users to create additional items by passing something similar to R where we do _options = list(create = TRUE)_

I don't seen an example of the options argument from the [R documentation](https://shiny.posit.co/r/reference/shiny/latest/selectinput) in the [python documentation](https://shiny.posit.co/py/api/ui.input_selectize.html) but perhaps I am missing something obvious

         options
         A list of options. See the documentation of selectize.js(https://selectize.dev/docs/usage) for possible options (character 
        option values inside [base::I()](https://rdrr.io/r/base/AsIs.html) will be treated as literal JavaScript code; see 
        [renderDataTable()](https://shiny.posit.co/r/reference/shiny/latest/renderDataTable.html) for details).

thanks a million,

Iain

**Comment by schloerke** [comment] 2023-11-01 14:29
Duplicate of https://github.com/posit-dev/py-shiny/issues/158 . Closing here

**Closed by schloerke** 2023-11-01 14:29 UTC
