### ISSUE TITLE
Shiny create: Error using Custom JavaScript Output Component template

### ISSUE THREAD

**Issue by btackett3** [posit-dev/py-shiny#959] opened 2024-01-02 21:47 UTC
```
➜  abc cd example-app 
➜  example-app ls
__pycache__ app.py
➜  example-app shiny run app.py
Traceback (most recent call last):
  File "/Users/briantackett/.pyenv/versions/checkrs-tew/bin/shiny", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/shiny/_main.py", line 164, in run
    return run_app(
           ^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/shiny/_main.py", line 338, in run_app
    uvicorn.run(  # pyright: ignore[reportUnknownMemberType]
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/envs/checkrs-tew/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/briantackett/.pyenv/versions/3.11.3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/briantackett/ppm/abc/example-app/app.py", line 1, in <module>
    from abc import abc, render_abc
ImportError: cannot import name 'abc' from 'abc' (/Users/briantackett/.pyenv/versions/3.11.3/lib/python3.11/abc.py)
```

Steps to reproduce:
```
? Which template would you like to use?: Custom JavaScript Component
? What kind of component do you want to build?: Output component
? What do you want to name your component?  Name must be dash-delimited and all lowercase. E.g. 'my-component-name' abc
? Enter destination directory: ../abc
Setting up abc component package...

cd ../abc
npm install
npm run build
pip install -e .
cd example-app 
shiny run app.py
```

**Comment by gshotwell** [comment] 2024-01-03 15:09
This is caused by a name conflict between your module (abc) and the built in python `abc` module "Abstract Base Class". I'm not sure there's much we can do to protect folks against that error, so I'm going to go ahead and close this.

**Closed by gshotwell** 2024-01-03 15:09 UTC
Labels: needs-triage

**Comment by gshotwell** [comment] 2024-01-03 17:18
I just realized that we can validate for standard and built-in module names, so this is actually something we can protect the user from. 

```
def is_standard_module(name: str) -> bool:
    builtin_modules = sys.builtin_module_names
    standard_lib = [
        module
        for _, module, _ in pkgutil.iter_modules()
        if module not in sys.builtin_module_names
    ]
    return name in builtin_modules or name in standard_lib

```
