### ISSUE TITLE
Padding broken in current pypi build?

### ISSUE THREAD

**Issue by jcheng5** [posit-dev/py-shiny#754] opened 2023-10-07 18:38 UTC
<img width="1461" alt="image" src="https://github.com/posit-dev/py-shiny/assets/129551/2d1827ae-efd9-491d-90be-02f5f6436b1c">

```
from shiny import App, render, ui
from shiny import experimental as x

app_ui = x.ui.page_sidebar(
    x.ui.sidebar("Hello"),
    "Hello"
)

app = App(app_ui, None)
```

Looks fine on shinylive.io but not when I just `pip install -U shiny`

**Comment by cpsievert** [comment] 2023-10-10 19:09
I haven't been able to reproduce this -- maybe double-check that you can with after disabling the browser cache?

**Comment by wch** [comment] 2024-02-28 05:31
Closing because the sidebar has been revamped since this issue was created.

**Closed by wch** 2024-02-28 05:31 UTC
